### ISSUE TITLE
주요 기능: 목록 페이지 개선 작업

### ISSUE THREAD

**Issue by KorpoQ** [wonsik3686/wine#167]
### @todo
- [x] - 더블 슬라이더 API 개선
- [x] - 와인 목록/와인 카드/이미지가 일부 잘리는 현상 수정
- [x] - 상단 와인 카드의 별점 표기 소수점 1자리까지
- [x] - 와인 등록 모달 undefined 버그 해결
- [x] - 가져온 와인이 없으면 '와인이 없어요'
- [x] - 검색 기능 미작동 수정
- [x] - 무한 스크롤 개선
- [x] - 와인 등록 버튼에 대한 로그인 검증 추가
